export const SITE_CONFIG = {
  name: "Gaber Usef",
  shortName: "Gaber",
  title: "Gaber Usef | Frontend Engineer & Web Developer",
  description:
    "Portfolio of Gaber Usef, a Frontend Engineer specializing in high-performance web applications, modern interactive UIs, React, and Next.js.",
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://gaberuseff.info",
  email: "dev.gaber@gmail.com",
  author: {
    name: "Gaber Usef",
    url: "https://gaberuseff.info",
    email: "dev.gaber@gmail.com",
    jobTitle: "Frontend Engineer & Web Developer",
  },
  socials: {
    github: "https://github.com/gaberuseff",
    linkedin: "https://www.linkedin.com/in/gaberuseff",
    facebook: "https://facebook.com/gaberuseff",
    whatsapp: "https://wa.me/201500223440",
  },
  skills: [
    "Frontend Development",
    "React.js",
    "Next.js",
    "JavaScript (ES6+)",
    "TypeScript",
    "Tailwind CSS",
    "UI/UX Engineering",
    "Web Performance Optimization",
    "Responsive Web Design",
    "State Management",
    "RESTful APIs & Supabase",
  ],
  keywords: [
    "Gaber Usef",
    "Gaber Useff",
    "Frontend Engineer",
    "Frontend Developer",
    "مطور واجهات أمامية",
    "مهندس برمجيات",
    "جابر يوسف",
    "React Developer",
    "Next.js Developer",
    "Web Developer Egypt",
    "Portfolio",
    "Web Applications",
    "Full-stack Solutions",
    "Modern Web Design",
    "Tailwind CSS",
    "JavaScript Developer",
  ],
  ogImage: "https://gaberuseff.info/imgs/logo.png",
};
